# Generated by Django 3.0.6 on 2020-05-09 14:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("user_profiles", "0001_initial"),
        ("user_profiles", "0002_auto_20200509_1443"),
    ]

    initial = True

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("cities_light", "0009_add_subregion"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                (
                    "address_line_1",
                    models.CharField(
                        help_text="Street name and number.", max_length=256
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "address_postcode",
                    models.CharField(max_length=8, verbose_name="Postcode"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Valid UK phone number (optional).",
                        max_length=32,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please enter a valid UK phone number.",
                                regex="^\\(?(?:\\+44)?\\)?[#()\\s\\d-]{,24}$",
                            )
                        ],
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        help_text="Valid UK mobile number.",
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please enter a valid UK phone number.",
                                regex="^\\(?(?:\\+44)?\\)?[#()\\s\\d-]{,24}$",
                            )
                        ],
                    ),
                ),
                (
                    "address_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cities_light.City",
                        verbose_name="City",
                    ),
                ),
            ],
        ),
    ]
