# Generated by Django 3.0.6 on 2020-05-09 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Valid UK phone number (optional).",
                max_length=32,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter a valid UK phone number.",
                        regex="^\\(?(?:\\+44)?\\)?[#()\\s\\d-]{,24}$",
                    )
                ],
            ),
        ),
    ]
