#!/bin/sh

python3 -m venv .venv
. .venv/bin/activate
pip install -r requirements.txt
python manage.py migrate
python manage.py loaddata fixtures/setup.json  # allauth SocialApp settings
python manage.py loaddata fixtures/geo.json  # cities_light City records
